repos:
  # Ordenar imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Formateador
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3

  # Linter rápido
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # Linter más estricto
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        additional_dependencies: []