CREATE TABLE datalogs (    
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    state BOOLEAN DEFAULT false
);

INSERT INTO datalogs(state) VALUES (false);